{
 "title": "Spring Batch Prometheus",
 "description": "Dashboard for Spring Batch applications instrumented with Micrometer",
 "tags": [
  "java",
  "micrometer",
  "cf",
  "spring-batch"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "org_name",
    "label": "Org Name",
    "query": "label_values(system_cpu_count, org_name)"
   },
   {
    "name": "space_name",
    "label": "Space Name",
    "query": "label_values(system_cpu_count{org_name=\"$org_name\"}, space_name)"
   },
   {
    "name": "app_name",
    "label": "App Name",
    "query": "label_values(system_cpu_count{org_name=\"$org_name\", space_name=\"$space_name\"}, app_name)"
   },
   {
    "name": "cf_instance_id",
    "label": "CF Instance ID",
    "query": "label_values(system_cpu_count{org_name=\"$org_name\", space_name=\"$space_name\", app_name =\"$app_name\"}, cf_instance_id)"
   }
  ]
 },
 "panels": [
  { "title": "Quick Facts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(process_uptime_seconds{app_name=~\"$app_name\", cf_instance_id=~\"$cf_instance_id\"})"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(process_start_time_seconds{app_name=~\"$app_name\", cf_instance_id=~\"$cf_instance_id\"}*1000)"
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\", app_name=~\"$app_name\", cf_instance_id=~\"$cf_instance_id\"})*100/sum(jvm_memory_max_bytes{area=\"heap\", app_name=~\"$app_name\", cf_instance_id=~\"$cf_instance_id\"})"
    }
   ]
  },
  {
   "title": "Non-Heap used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"nonheap\", app_name=~\"$app_name\", cf_instance_id=~\"$cf_instance_id\"})*100/sum(jvm_memory_max_bytes{area=\"nonheap\", app_name=~\"$app_name\", cf_instance_id=~\"$cf_instance_id\"})"
    }
   ]
  },
  { "title": "JVM Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "JVM Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\", app_name=~\"$app_name\", cf_instance_id=~\"$cf_instance_id\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{area=\"heap\", app_name=~\"$app_name\", cf_instance_id=~\"$cf_instance_id\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{area=\"heap\", app_name=~\"$app_name\", cf_instance_id=~\"$cf_instance_id\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Non-Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"nonheap\", app_name=~\"$app_name\", cf_instance_id=~\"$cf_instance_id\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{area=\"nonheap\", app_name=~\"$app_name\", cf_instance_id=~\"$cf_instance_id\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{area=\"nonheap\",app_name=~\"$app_name\", cf_instance_id=~\"$cf_instance_id\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{app_name=~\"$app_name\", cf_instance_id=~\"$cf_instance_id\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{app_name=~\"$app_name\", cf_instance_id=~\"$cf_instance_id\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{app_name=~\"$app_name\", cf_instance_id=~\"$cf_instance_id\"})",
     "legendFormat": "max"
    },
    {
     "expr": "process_memory_rss_bytes{app_name=~\"$app_name\", cf_instance_id=~\"$cf_instance_id\"}",
     "legendFormat": "rss"
    },
    {
     "expr": "process_memory_pss_bytes{app_name=~\"$app_name\", cf_instance_id=~\"$cf_instance_id\"}",
     "legendFormat": "pss"
    },
    {
     "expr": "process_memory_swap_bytes{app_name=~\"$app_name\", cf_instance_id=~\"$cf_instance_id\"}",
     "legendFormat": "swap"
    },
    {
     "expr": "process_memory_swappss_bytes{app_name=~\"$app_name\", cf_instance_id=~\"$cf_instance_id\"}",
     "legendFormat": "swappss"
    },
    {
     "expr": "process_memory_pss_bytes{app_name=~\"$app_name\", cf_instance_id=~\"$cf_instance_id\"} + process_memory_swap_bytes{app_name=~\"$app_name\", cf_instance_id=~\"$cf_instance_id\"}",
     "legendFormat": "phys (pss+swap)"
    }
   ]
  },
  {
   "title": "JVM Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_live{app_name=~\"$app_name\", cf_instance_id=~\"$cf_instance_id\"} or jvm_threads_live_threads{app_name=~\"$app_name\", cf_instance_id=~\"$cf_instance_id\"}",
     "legendFormat": "live"
    },
    {
     "expr": "jvm_threads_daemon{app_name=~\"$app_name\", cf_instance_id=~\"$cf_instance_id\"} or jvm_threads_daemon_threads{app_name=~\"$app_name\", cf_instance_id=~\"$cf_instance_id\"}",
     "legendFormat": "daemon"
    },
    {
     "expr": "jvm_threads_peak{app_name=~\"$app_name\", cf_instance_id=~\"$cf_instance_id\"} or jvm_threads_peak_threads{app_name=~\"$app_name\", cf_instance_id=~\"$cf_instance_id\"}",
     "legendFormat": "peak"
    },
    {
     "expr": "process_threads{app_name=~\"$app_name\", cf_instance_id=~\"$cf_instance_id\"}",
     "legendFormat": "process"
    }
   ]
  },
  { "title": "Spring Batch Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Job duration max",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "spring_batch_job_seconds_max{app_name=~\"$app_name\", cf_instance_id=~\"$cf_instance_id\"}",
     "legendFormat": "{{name}} {{status}}"
    }
   ]
  },
  {
   "title": "Job executions rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "spring_batch_job_seconds_count{app_name=~\"$app_name\", cf_instance_id=~\"$cf_instance_id\"}",
     "legendFormat": "{{name}} {{status}}"
    }
   ]
  },
  {
   "title": "Job execution time distribution",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(rate(spring_batch_job_seconds_bucket{le=~\"[1-9]+\\\\.\\\\d+|\\\\+Inf\", app_name=~\"$app_name\", cf_instance_id=~\"$cf_instance_id\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Job failure rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(spring_batch_job_seconds_count{status=\"FAILED\", app_name=~\"$app_name\", cf_instance_id=~\"$cf_instance_id\"}[1m])) by (name, status)) / (sum(rate(spring_batch_job_seconds_count{app_name=~\"$app_name\", cf_instance_id=~\"$cf_instance_id\"}[1m])) by (name, status))",
     "legendFormat": "{{name}} {{status}}"
    }
   ]
  },
  {
   "title": "Item read throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(spring_batch_item_read_seconds_count{app_name=~\"$app_name\", cf_instance_id=~\"$cf_instance_id\"}[1m])",
     "legendFormat": "read {{status}}"
    }
   ]
  },
  {
   "title": "Item write throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(spring_batch_chunk_write_seconds_count{app_name=~\"$app_name\", cf_instance_id=~\"$cf_instance_id\"}[1m])",
     "legendFormat": "write {{status}}"
    }
   ]
  }
 ]
}